name: CI
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
  workflow_dispatch:
jobs:
  finalize:
    timeout-minutes: 10
    needs: [test, docs]
    if: always()
    runs-on: ubuntu-latest # GitHub-hosted runners
    steps:
      - run: |
          echo test: ${{ needs.test.result }}
          echo doctest: ${{ needs.docs.result }}
      - run: exit 1
        if: |
          (needs.test.result != 'success') ||
          (needs.docs.result != 'success')
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'min'
          - '1' # automatically expands to the latest stable 1.x release of Julia
          - 'pre'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    # needed to allow julia-actions/cache to delete old caches that it has created
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
